# http://localhost:8081/swagger-ui/index.html#/

spring:
  application:
    name: sharing
    version: ${version:Неизвестная версия} # парсить pom.xml и тянуть версию оттуда
  datasource:
    database-name-postfix: db
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${VIRTUAL_PRIVATE_CLOUD_PUBLIC_IP}:${DATASOURCE_PORT}/${spring.application.name}_${spring.datasource.database-name-postfix}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:database.migrations
    schemas:
      - user
      - dictionary
      - sharing
      - system
    default-schema: system
  config:
    import: classpath:.env.properties

server:
  port: 8081
  ssl:
    enabled: false